[package]
name = "space"
version = "0.4.0"
authors = ["jonakieling"]

[dependencies]
ggez = "^0.4"
rand = "^0.5"
rayon = "^1.0"
serde = "^1.0"
serde_derive = "^1.0"
bincode = "^1.0"
tar = "^0.4"
specs = "^0.11"
specs-derive = "^0.2"